management.metrics:
  enable.jvm: true
  export.prometheus.enabled: true
  distribution.sla.http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s
  tags.application: @project.name@
  distribution.percentiles-histogram:
    http.server.requests: true
    resilience4j.circuitbreaker.calls: true
    resilience4j.ratelimiter.calls: true

management.endpoints:
  web.exposure.include: '*'
  health.show-details: always

management.endpoint.health.show-details: always

management.health:
  diskspace.enabled: true
  circuitbreakers.enabled: true
  ratelimiters.enabled: true

info.app:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  encoding: @project.build.sourceEncoding@
  java.version: @java.version@

logging:
  level:
    io.github.resilience4j: DEBUG