name: Build and Publish Workflow

on:
  push:
    branches: [master]

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Change directory
        run: |
          cd java-resilience4j-lab

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date for version
        id: date
        run: echo "::set-output name=date::$(date +'%s')"

      - name: Build the Docker image
        run: cd java-resilience4j-lab && docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/lab-java4j:$TAG_NAME
        env:
          TAG_NAME: v${{ steps.date.outputs.date }}

      - name: Push image to HUB
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lab-java4j:${TAG_NAME}
        env:
          TAG_NAME: v${{ steps.date.outputs.date }}