name: CI/CD Workflow

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Java Application
        run: |
          cd java-resilience4j-lab
          ./mvnw clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests
        run: |
          cd java-resilience4j-lab
          ./mvnw test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Make clientsh.sh executable
        run: chmod +x client.sh

      - name: Run ClientSH Script
        run: |
          ./client.sh

      - name: Validate Prometheus Metrics
        run: |
          curl http://localhost:8080/actuator/prometheus
